version: '3'

services:
  apache:
    image: 'bitnami/apache:latest'
    container_name: my_apache
    ports:
      - '80:80'
    volumes:
      - ./htdocs:/app
      - ./config/apache:/opt/bitnami/apache/conf
      - ./logs/apache:/opt/bitnami/apache/logs
    environment:
      - ALLOW_OVERRIDE=all

  mysql:
    image: 'mysql:latest'
    container_name: my_mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
      - ./sql:/docker-entrypoint-initdb.d # added volume to map SQL script
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=my_database # added environment variable for database name

  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: my_phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=my-secret-pw
