version: '3.8' # Updated to version 3.8

services:
  mysql:
    image: 'mysql:latest'
    container_name: locations_service_db # Added container_name
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql # Updated volume location for data, clean after pw changes for example
      - ./config/mysql:/etc/mysql/conf.d # Added volume for MySQL configuration
      - ./sql:/docker-entrypoint-initdb.d # Added volume to map SQL script
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # Changed to YAML format
      MYSQL_DATABASE: locations # Changed to YAML format
